language: python
python:
  - "2.7"
before_install:
  - sudo apt-get update 
  - sudo apt-get install -y python-numpy cython
install: 
  - sudo python setup.py --cython install
script: 
  - "python -m doctest manual.txt" 

