sudo: false
dist: trusty
language: python
python:
  - "2.7"

before_install:
  - apt-get update 
  - apt-get install -y python-pip python-numpy cython

install: 
  - python setup.py --cython install

script: 
  - mkdir test && cd test && python -m doctest ../manual.txt

