sudo: false
dist: trusty
language: bash

before_install:
  - curl https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh > conda.sh
  - bash conda.sh -b -p $HOME/conda
  - $HOME/conda/bin/conda install -y numpy cython
  - export PATH=$HOME/conda/bin:$PATH

install:
  - python setup.py --cython install

script: 
  - python -m doctest -v manual.txt

